# Generated by Django 5.2.9 on 2025-12-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Bairro"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bairro",
                "verbose_name_plural": "Bairros",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EscolaNucleo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Núcleo"),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endereço"
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Escola Núcleo",
                "verbose_name_plural": "Escolas Núcleo",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Escola"),
                ),
                (
                    "codigo_inep",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Código INEP",
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Endereço"
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "nucleo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escolas_lotacao",
                        to="os_app.escolanucleo",
                        verbose_name="Escola Núcleo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escola de Lotação",
                "verbose_name_plural": "Escolas de Lotação",
                "ordering": ["nucleo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto do professor (opcional)",
                        null=True,
                        upload_to="professores/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                ("telefone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "matricula",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "area_atuacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione uma área"),
                            ("lingua_portuguesa", "Língua Portuguesa"),
                            ("matematica", "Matemática"),
                            ("historia", "História"),
                            ("geografia", "Geografia"),
                            ("ciencias", "Ciências"),
                            ("fisica", "Física"),
                            ("quimica", "Química"),
                            ("biologia", "Biologia"),
                            ("educacao_fisica", "Educação Física"),
                            ("arte", "Arte"),
                            (
                                "lingua_estrangeira_ingles",
                                "Língua Estrangeira - Inglês",
                            ),
                            (
                                "lingua_estrangeira_espanhol",
                                "Língua Estrangeira - Espanhol",
                            ),
                            ("ensino_religioso", "Ensino Religioso"),
                            ("filosofia", "Filosofia"),
                            ("sociologia", "Sociologia"),
                            ("literatura", "Literatura"),
                            ("redacao", "Redação"),
                            ("educacao_infantil", "Educação Infantil"),
                            ("anos_iniciais_ef", "Anos Iniciais do Ensino Fundamental"),
                            ("anos_finais_ef", "Anos Finais do Ensino Fundamental"),
                            ("ensino_medio", "Ensino Médio"),
                            ("gestao_escolar", "Gestão Escolar"),
                            ("coordenacao_pedagogica", "Coordenação Pedagógica"),
                            ("biblioteconomia", "Biblioteconomia"),
                            ("psicologia_escolar", "Psicologia Escolar"),
                            ("outras", "Outras"),
                        ],
                        max_length=50,
                        verbose_name="Área de Atuação",
                    ),
                ),
                ("endereco", models.CharField(max_length=150, verbose_name="Endereço")),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                ("cidade", models.CharField(max_length=50, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="os_app.bairro",
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="os_app.escola",
                        verbose_name="Escola de Lotação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["nome"],
            },
        ),
    ]
