# Generated by Django 5.2.9 on 2025-12-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Cargo"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="escola",
            options={
                "ordering": ["nome"],
                "verbose_name": "Escola de Lotação",
                "verbose_name_plural": "Escolas de Lotação",
            },
        ),
        migrations.AlterField(
            model_name="escola",
            name="nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escolas_lotacao",
                to="os_app.escolanucleo",
                verbose_name="Escola Núcleo",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="os_app.cargo",
                verbose_name="Cargo",
            ),
        ),
    ]
