# Generated by Django 5.2.9 on 2025-12-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0002_cargo_alter_escola_options_alter_escola_nucleo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo",
                "verbose_name_plural": "Motivos",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Série"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Série",
                "verbose_name_plural": "Séries",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="escola",
            name="bairro",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="escola",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="escola",
            name="numero",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="escola",
            name="zona",
            field=models.CharField(
                choices=[("rural", "Rural"), ("urbana", "Urbana")],
                default="urbana",
                max_length=10,
                verbose_name="Zona",
            ),
        ),
        migrations.AddField(
            model_name="escolanucleo",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="escolanucleo",
            name="codigo_inep",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Código INEP",
            ),
        ),
        migrations.AddField(
            model_name="escolanucleo",
            name="numero",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="escolanucleo",
            name="zona",
            field=models.CharField(
                choices=[("rural", "Rural"), ("urbana", "Urbana")],
                default="urbana",
                max_length=10,
                verbose_name="Zona",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="em_sala",
            field=models.CharField(
                blank=True,
                choices=[("sim", "SIM"), ("nao", "NÃO")],
                max_length=3,
                verbose_name="Em Sala",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="modalidade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione"),
                    ("ed_esp", "Ed. Esp"),
                    ("ed_inf", "Ed. Inf"),
                    ("eja", "EJA"),
                    ("fund_1", "Fund 1"),
                    ("fund_2", "Fund 2"),
                    ("ind", "Ind"),
                    ("fund", "Fund"),
                ],
                max_length=20,
                verbose_name="Modalidade",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="observacao_turmas",
            field=models.TextField(blank=True, verbose_name="Observação sobre Turmas"),
        ),
        migrations.AddField(
            model_name="professor",
            name="ref_global",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Ref. Global"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="situacao_funcional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione"),
                    ("acres", "Acrés"),
                    ("contr", "Contr"),
                    ("dobra", "Dobra"),
                    ("efetivo", "Efetivo"),
                ],
                max_length=20,
                verbose_name="Situação Funcional",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substituindo",
                to="os_app.professor",
                verbose_name="Substituto",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione"),
                    ("diurno", "Diurno"),
                    ("matutino", "Matutino"),
                    ("vespertino", "Vespertino"),
                    ("noturno", "Noturno"),
                ],
                max_length=20,
                verbose_name="Turno",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="motivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="os_app.motivo",
                verbose_name="Motivo",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="os_app.serie",
                verbose_name="Série",
            ),
        ),
    ]
