# Generated by Django 5.2.9 on 2025-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0003_motivo_serie_escola_bairro_escola_cep_escola_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bairro",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome do Bairro"),
        ),
        migrations.AlterUniqueTogether(
            name="bairro",
            unique_together={("nome", "cidade", "estado")},
        ),
    ]
