# Generated by Django 5.2.9 on 2025-12-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0004_alter_bairro_nome_alter_bairro_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="escolanucleo",
            name="bairro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escolas_nucleo",
                to="os_app.bairro",
                verbose_name="Bairro",
            ),
        ),
        migrations.AlterField(
            model_name="escola",
            name="bairro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escolas_dependentes",
                to="os_app.bairro",
                verbose_name="Bairro",
            ),
        ),
    ]
