# Generated by Django 5.2.9 on 2025-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0006_add_escola_nucleo"),
    ]

    operations = []
