# Generated by Django 5.2.9 on 2026-01-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0007_add_escola_nucleo"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="materias",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Matérias que o professor leciona (separadas por vírgula)",
                verbose_name="Matérias",
            ),
        ),
    ]
