# Generated by Django 5.2.9 on 2026-01-23 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0008_professor_materias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login no Sistema"),
                            ("LOGOUT", "Logout do Sistema"),
                            ("CREATE", "Criação de Registro"),
                            ("UPDATE", "Atualização de Registro"),
                            ("DELETE", "Exclusão de Registro"),
                            ("VIEW", "Visualização de Registro"),
                            ("SEARCH", "Busca/Filtro"),
                            ("EXPORT", "Exportação de Dados"),
                            ("IMPORT", "Importação de Dados"),
                            ("REPORT", "Geração de Relatório"),
                            ("PRINT", "Impressão de Documento"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Professor", "Professor"),
                            ("Escola", "Escola"),
                            ("EscolaNucleo", "Escola Núcleo"),
                            ("Cargo", "Cargo"),
                            ("Bairro", "Bairro"),
                            ("Serie", "Série"),
                            ("Motivo", "Motivo"),
                            ("Usuario", "Usuário"),
                            ("Sistema", "Sistema"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "objeto_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID do Objeto"
                    ),
                ),
                (
                    "objeto_repr",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Representação do Objeto",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "dados_anteriores",
                    models.JSONField(
                        blank=True,
                        help_text="Estado anterior do registro (para UPDATE/DELETE)",
                        null=True,
                        verbose_name="Dados Anteriores",
                    ),
                ),
                (
                    "dados_novos",
                    models.JSONField(
                        blank=True,
                        help_text="Estado novo do registro (para CREATE/UPDATE)",
                        null=True,
                        verbose_name="Dados Novos",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Navegador/dispositivo utilizado",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                ("sucesso", models.BooleanField(default=True, verbose_name="Sucesso")),
                (
                    "mensagem_erro",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["-data_hora"], name="os_app_loga_data_ho_d5c9e3_idx"
                    ),
                    models.Index(
                        fields=["usuario", "-data_hora"],
                        name="os_app_loga_usuario_c57cd3_idx",
                    ),
                    models.Index(
                        fields=["acao", "-data_hora"],
                        name="os_app_loga_acao_7f85ec_idx",
                    ),
                    models.Index(
                        fields=["modelo", "objeto_id"],
                        name="os_app_loga_modelo_34eff6_idx",
                    ),
                ],
            },
        ),
    ]
