# Generated by Django 5.2.9 on 2026-01-23 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0009_logauditoria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("GESTOR", "Gestor"),
                            ("COORDENADOR", "Coordenador"),
                            ("CONSULTA", "Apenas Consulta"),
                        ],
                        default="CONSULTA",
                        max_length=20,
                        verbose_name="Tipo de Usuário",
                    ),
                ),
                (
                    "cargo_funcao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo/Função"
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="usuarios/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "pode_criar_professor",
                    models.BooleanField(
                        default=False, verbose_name="Pode Criar Professores"
                    ),
                ),
                (
                    "pode_editar_professor",
                    models.BooleanField(
                        default=False, verbose_name="Pode Editar Professores"
                    ),
                ),
                (
                    "pode_excluir_professor",
                    models.BooleanField(
                        default=False, verbose_name="Pode Excluir Professores"
                    ),
                ),
                (
                    "pode_gerar_relatorios",
                    models.BooleanField(
                        default=True, verbose_name="Pode Gerar Relatórios"
                    ),
                ),
                (
                    "pode_exportar_dados",
                    models.BooleanField(
                        default=False, verbose_name="Pode Exportar Dados"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Usuário pode acessar o sistema",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "ultimo_acesso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acesso"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "escola_vinculada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Escola à qual o usuário está vinculado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="os_app.escola",
                        verbose_name="Escola Vinculada",
                    ),
                ),
                (
                    "nucleo_vinculado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Núcleo ao qual o usuário está vinculado",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="os_app.escolanucleo",
                        verbose_name="Núcleo Vinculado",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "ordering": ["usuario__username"],
            },
        ),
    ]
