# Generated by Django 5.2.9 on 2026-01-27 22:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0010_perfilusuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilusuario",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="perfilusuario",
            name="ultimo_acesso",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="cep",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="escola",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="materias",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="motivo",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="observacao_turmas",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="substituto",
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 1, 27, 22, 19, 54, 578958, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_criar_escola_dependente",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para cadastrar novas escolas dependentes",
                verbose_name="Pode Criar Escolas Dependentes",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_criar_escola_nucleo",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para cadastrar novas escolas núcleo",
                verbose_name="Pode Criar Escolas Núcleo",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_editar_escola_dependente",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para editar dados de escolas dependentes",
                verbose_name="Pode Editar Escolas Dependentes",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_editar_escola_nucleo",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para editar dados de escolas núcleo",
                verbose_name="Pode Editar Escolas Núcleo",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_excluir_escola_dependente",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para excluir escolas dependentes",
                verbose_name="Pode Excluir Escolas Dependentes",
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="pode_excluir_escola_nucleo",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para excluir escolas núcleo",
                verbose_name="Pode Excluir Escolas Núcleo",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="professor",
            name="carga_horaria",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Carga Horária"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="disciplinas",
            field=models.CharField(
                blank=True,
                help_text="Separar disciplinas por vírgula",
                max_length=200,
                verbose_name="Disciplinas",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="escola_lotacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores",
                to="os_app.escola",
                verbose_name="Escola de Lotação",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="motivo_fora_sala",
            field=models.ForeignKey(
                blank=True,
                help_text="Preencher apenas se não estiver em sala",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="os_app.motivo",
                verbose_name="Motivo de não estar em sala",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="escola_vinculada",
            field=models.ForeignKey(
                blank=True,
                help_text="Escola à qual o usuário está vinculado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="os_app.escola",
                verbose_name="Escola Vinculada",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="usuarios/fotos/", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="nucleo_vinculado",
            field=models.ForeignKey(
                blank=True,
                help_text="Núcleo ao qual o usuário está vinculado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="os_app.escolanucleo",
                verbose_name="Núcleo Vinculado",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="pode_criar_professor",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para cadastrar novos professores",
                verbose_name="Pode Criar Professores",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="pode_editar_professor",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para editar dados de professores",
                verbose_name="Pode Editar Professores",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="pode_excluir_professor",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para excluir professores",
                verbose_name="Pode Excluir Professores",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="pode_exportar_dados",
            field=models.BooleanField(
                default=False,
                help_text="Permissão para exportar dados (Excel, PDF, etc)",
                verbose_name="Pode Exportar Dados",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="pode_gerar_relatorios",
            field=models.BooleanField(
                default=True,
                help_text="Permissão para gerar relatórios do sistema",
                verbose_name="Pode Gerar Relatórios",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="area_atuacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione uma área"),
                    ("lingua_portuguesa", "Língua Portuguesa"),
                    ("matematica", "Matemática"),
                    ("historia", "História"),
                    ("geografia", "Geografia"),
                    ("ciencias", "Ciências"),
                    ("fisica", "Física"),
                    ("quimica", "Química"),
                    ("biologia", "Biologia"),
                    ("educacao_fisica", "Educação Física"),
                    ("arte", "Arte"),
                    ("lingua_estrangeira_ingles", "Língua Estrangeira - Inglês"),
                    ("lingua_estrangeira_espanhol", "Língua Estrangeira - Espanhol"),
                    ("ensino_religioso", "Ensino Religioso"),
                    ("filosofia", "Filosofia"),
                    ("sociologia", "Sociologia"),
                    ("literatura", "Literatura"),
                    ("redacao", "Redação"),
                    ("educacao_infantil", "Educação Infantil"),
                    ("anos_iniciais_ef", "Anos Iniciais do Ensino Fundamental"),
                    ("anos_finais_ef", "Anos Finais do Ensino Fundamental"),
                    ("ensino_medio", "Ensino Médio"),
                    ("gestao_escolar", "Gestão Escolar"),
                    ("coordenacao_pedagogica", "Coordenação Pedagógica"),
                    ("biblioteconomia", "Biblioteconomia"),
                    ("psicologia_escolar", "Psicologia Escolar"),
                    ("outras", "Outras"),
                ],
                max_length=100,
                verbose_name="Área de Atuação",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="bairro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores",
                to="os_app.bairro",
                verbose_name="Bairro",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="em_sala",
            field=models.BooleanField(default=True, verbose_name="Em Sala"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="escola_nucleo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores_nucleo",
                to="os_app.escolanucleo",
                verbose_name="Escola Núcleo",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="situacao_funcional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Selecione"),
                    ("acrescimo", "Acréscimo"),
                    ("contratado", "Contratado"),
                    ("dobra", "Dobra"),
                    ("efetivo", "Efetivo"),
                ],
                max_length=20,
                verbose_name="Situação Funcional",
            ),
        ),
    ]
