# Generated by Django 5.2.9 on 2026-01-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0011_remove_perfilusuario_data_cadastro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="professor",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="professor",
            name="endereco",
            field=models.CharField(blank=True, max_length=200, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="professor",
            name="estado",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
    ]
