# Generated by Django 5.2.9 on 2026-02-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("os_app", "0012_professor_endereco_campos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, verbose_name="Telefone"),
        ),
    ]
